operator:
  resources: {}
  extraEnvs: {}

image:
  registry: docker.io
  name: vault-secrets-operator
  pullPolicy: IfNotPresent

vault:
  enabled: true
  dev:
    enabled: true
    devRootToken: myroot