apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaultsecrets.erizzardi.mine.io
spec:
  group: erizzardi.mine.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              required: ["data", "secretEngine", "secretPath"]
              type: object
              properties:
                secretEngine:
                  type: string
                secretPath:
                  type: string
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
  scope: Namespaced
  names:
    plural: vaultsecrets
    singular: vaultsecret
    kind: VaultSecret
    shortNames:
    - vs